# Form implementation generated from reading ui file 'C:\Users\vuquo\OneDrive\Máy tính\K22416C\salesmanegemant\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_He_Thong_may_Hoc_ABC(object):
    def setupUi(self, He_Thong_may_Hoc_ABC):
        He_Thong_may_Hoc_ABC.setObjectName("He_Thong_may_Hoc_ABC")
        He_Thong_may_Hoc_ABC.resize(997, 488)
        self.centralwidget = QtWidgets.QWidget(parent=He_Thong_may_Hoc_ABC)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 20, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 90, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Line_Edit_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Line_Edit_username.setGeometry(QtCore.QRect(310, 150, 621, 41))
        self.Line_Edit_username.setObjectName("Line_Edit_username")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 200, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Line_edit_Password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Line_edit_Password.setGeometry(QtCore.QRect(310, 260, 621, 41))
        self.Line_edit_Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Line_edit_Password.setObjectName("Line_edit_Password")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(310, 320, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(390, 370, 181, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\vuquo\\OneDrive\\Máy tính\\K22416C\\salesmanegemant\\ui\\../images/login_button_image.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_login.setIcon(icon)
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(690, 370, 181, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\vuquo\\OneDrive\\Máy tính\\K22416C\\salesmanegemant\\ui\\../images/exit_image.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_exit.setIcon(icon1)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 301, 261))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\vuquo\\OneDrive\\Máy tính\\K22416C\\salesmanegemant\\ui\\../images/2203549_admin_avatar_human_login_user_icon.png"))
        self.label_4.setObjectName("label_4")
        He_Thong_may_Hoc_ABC.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=He_Thong_may_Hoc_ABC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 26))
        self.menubar.setObjectName("menubar")
        He_Thong_may_Hoc_ABC.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=He_Thong_may_Hoc_ABC)
        self.statusbar.setObjectName("statusbar")
        He_Thong_may_Hoc_ABC.setStatusBar(self.statusbar)

        self.retranslateUi(He_Thong_may_Hoc_ABC)
        self.pushButton_exit.clicked.connect(He_Thong_may_Hoc_ABC.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(He_Thong_may_Hoc_ABC)

    def retranslateUi(self, He_Thong_may_Hoc_ABC):
        _translate = QtCore.QCoreApplication.translate
        He_Thong_may_Hoc_ABC.setWindowTitle(_translate("He_Thong_may_Hoc_ABC", "MainWindow"))
        self.label.setText(_translate("He_Thong_may_Hoc_ABC", "Đăng nhập hệ thống"))
        self.label_2.setText(_translate("He_Thong_may_Hoc_ABC", "User name: "))
        self.label_3.setText(_translate("He_Thong_may_Hoc_ABC", "Password:"))
        self.checkBox.setText(_translate("He_Thong_may_Hoc_ABC", "Lưu thông tin đăng nhập"))
        self.pushButton_login.setText(_translate("He_Thong_may_Hoc_ABC", "Đăng nhập"))
        self.pushButton_exit.setText(_translate("He_Thong_may_Hoc_ABC", "Thoát"))
